### PR TITLE
feat: add macro and visualization support to simg4ox

### PR DESCRIPTION
**Pull request by plexoos**
See #18 for motivation

### CODE REVIEW

**Comment by plexoos** [comment]
It works for me, but it would be better if a GUI window didn't pop up by default and only appeared when a CLI option is specified.

**Comment by ggalgoczi** [comment]
Pushed a commit with the following changes:
-m CLI argument chooses macro file, default is vis.mac

Added an example macro without vis: run1.mac

**Comment by plexoos** [comment]
@ggalgoczi Would you like to add anything else to the PR?

**Comment by ggalgoczi** [comment]
Nothing else to add right now! Thanks for taking care of this!

**Comment by plexoos** [comment]
Thank you Gabor!

**Pull request merged**
